bdloc_app:
    resource: "@BdlocAppBundle/Controller/"
    type:     annotation
    prefix:   /


# app/config/routing.yml
login_check:
    path: /login_check
logout:
    path: /logout


gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"
    prefix: /_gcb