<?php

namespace Bdloc\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Doctrine\ORM\QueryBuilder;

/**
 * CartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends EntityRepository
{

    public function countBooks()
	{

	   $query = $this->createQueryBuilder('b')
	                  ->select('COUNT(b)')     
	                  ->getQuery();
	           
	  return $query->getSingleScalarResult();
	}

	public function getBooks($page, $nombreParPage = "", $direction = 'DESC', $entity = 'b.dateCreated', $series = array())
    {

        $qb = $this->getEntityManager()->createQueryBuilder();

        			  $qb->select(array('b', 'a', 's'))
        			  ->from('Bdloc\AppBundle\Entity\Book', 'b')
        			  ->leftJoin('b.illustrator', 'a')
        			  ->leftJoin('b.serie', 's');

        			  foreach( $series as $serie ) {
        			  	$params = $serie->getStyle();
        			  	$paramslength = strlen($params);
        			  	for( $i = 0; $i <= $paramslength; $i++) {
				    		$qb->orWhere ('s.style = ' . $params[$i] . '');
				    	}

				      }
        	          $qb->setFirstResult(($page-1) * $nombreParPage)
        			  ->setMaxResults($nombreParPage)
        			  ->orderBy($entity, $direction)
                      ;


        return $qb->getQuery()->getResult();
    }

    //  "' . $serie->getStyle() . '"

	public function findBookWithTitle($title)
    {

        $query = $this->createQueryBuilder('b')
                      ->where('b.title LIKE :title')
                      ->setParameters(array('title' => '%' . $title . '%'))
                      ->getQuery();

        return $query->getResult();
    }		

}
