<?php

namespace Bdloc\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * CartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends EntityRepository
{

    public function countBooks()
	{

	   $query = $this->createQueryBuilder('b')
	                  ->select('COUNT(b)')     
	                  ->getQuery();
	           
	  return $query->getSingleScalarResult();
	}

	public function getBooks($page, $nombreParPage = "", $direction = 'DESC', $entity = 'b.dateCreated')
    {

        $query = $this->createQueryBuilder('b')
        	          ->setFirstResult(($page-1) * $nombreParPage)
        			  ->setMaxResults($nombreParPage)
        			  ->orderBy($entity, $direction)
                      ->getQuery();


        return $query->getResult();
    }

	public function findBookWithTitle($title)
    {

        $query = $this->createQueryBuilder('b')
                      ->where('b.title LIKE :title')
                      ->setParameters(array('title' => '%' . $title . '%'))
                      ->getQuery();

        return $query->getResult();
    }	

}
